---
title: "GND Initial Analysis Tables"
author: "Felix Westcott"
date: '2022-06-15'
output: html_document
---

```{r setup, include=FALSE, Load data and clean}

library(tidyverse)
library(ggplot2)
library(readxl)
library(xlsx)
library(dplyr)
library(ggpubr)
library(ggsci)
library(rstatix)
library (cowplot)
library(DT)

#Load data
All_data <- read_excel("FHS_Database_2020 Final.xlsx", sheet = 1)

#Remove unwanted columns
drops <- c("Visit","Intervention", "Comments")
All_data <- All_data[ , !(names(All_data) %in% drops)]

```

``` {r, Split data}

All_data_split_df <- mutate(All_data, "Liver fat" = if_else(All_data$`IHTG (%)`<=5.56, "Low","High"), "Insulin" = if_else(All_data$`Insulin (nmol/L)`<=11.2, "Low","High"))

```
``` {r}

Liver_fat_counts <- All_data_split_df %>% 
  group_by(`Liver fat`) %>% count(Sex)

Insulin_counts <- All_data_split_df %>% 
  group_by(`Insulin`) %>% count(Sex)

Liver_fat_counts

Insulin_counts

```


``` {r, Medians}

Liver_fat_medians <- All_data_split_df %>% 
  group_by(`Liver fat`) %>% 
  summarize(
    "IHTG (%)" = median(`IHTG (%)`,na.rm = TRUE),
    "Age" = median(`Age`, na.rm = TRUE), 
    "Weight (kg)" = median(`Weight (kg)`, na.rm = TRUE),  
    "BMI" = median(`BMI`, na.rm = TRUE), 
    "Waist Circumference (cm)" = median(`Waist Circumference (cm)`, na.rm = TRUE), 
    "Fat mass (%)" = median (`Fat mass (%)`, na.rm = TRUE), 
    "Lean mass (%)" = median(`Lean mass (%)`,na.rm = TRUE), 
    "Visceral fat mass (%)" = median(`Visceral fat mass (%)`,na.rm = TRUE),
    "Glucose (mmol/L)" = median(`Glucose (mmol/L)`,na.rm = TRUE),
    "Insulin (nmol/L)" = median(`Insulin (nmol/L)`,na.rm = TRUE),
    "HOMA-IR" = median(`HOMA-IR`,na.rm = TRUE),
    "NEFA (umol/L)" = median(`NEFA (umol/L)`,na.rm = TRUE),
    "TAG (umol/L)" = median(`TAG (umol/L)`,na.rm = TRUE),
    "3OHB (umol/L)" = median(`3OHB (umol/L)`,na.rm = TRUE),
    "Total Cholesterol (mmol/L)" = median(`Total Cholesterol (mmol/L)`,na.rm = TRUE),
    "HDL Cholesterol (mmol/L)" = median(`HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "Non-HDL Cholesterol (mmol/L)" = median(`Non-HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "DNL (%)" = median(`DNL (%)`,na.rm = TRUE),
    "DNL (umol/L)" = median(`DNL (umol/L)`,na.rm = TRUE),
    "frGNG (%)" = median(`frGNG (%)`,na.rm = TRUE),
    "GNG (mmol/L)" = median(`GNG (mmol/L)`,na.rm = TRUE),
    "GLY (mmol/L)" = median(`GLY (mmol/L)`,na.rm = TRUE))

Liver_fat_medians <- as.data.frame(t(Liver_fat_medians[1:2,2:23])) %>% rename("Median High" = V1, "Median Low" = V2)%>%round(digits = 1)

```


``` {r, Ranges}

Liver_fat_mins <- All_data_split_df %>% 
  group_by(`Liver fat`) %>% 
  summarize(
    "IHTG (%)" = min(`IHTG (%)`,na.rm = TRUE),
    "Age" = min(`Age`, na.rm = TRUE), 
    "Weight (kg)" = min(`Weight (kg)`, na.rm = TRUE),  
    "BMI" = min(`BMI`, na.rm = TRUE), 
    "Waist Circumference (cm)" = min(`Waist Circumference (cm)`, na.rm = TRUE), 
    "Fat mass (%)" = min (`Fat mass (%)`, na.rm = TRUE), 
    "Lean mass (%)" = min(`Lean mass (%)`,na.rm = TRUE), 
    "Visceral fat mass (%)" = min(`Visceral fat mass (%)`,na.rm = TRUE),
    "Glucose (mmol/L)" = min(`Glucose (mmol/L)`,na.rm = TRUE),
    "Insulin (nmol/L)" = min(`Insulin (nmol/L)`,na.rm = TRUE),
    "HOMA-IR" = min(`HOMA-IR`,na.rm = TRUE),
    "NEFA (umol/L)" = min(`NEFA (umol/L)`,na.rm = TRUE),
    "TAG (umol/L)" = min(`TAG (umol/L)`,na.rm = TRUE),
    "3OHB (umol/L)" = min(`3OHB (umol/L)`,na.rm = TRUE),
    "Total Cholesterol (mmol/L)" = min(`Total Cholesterol (mmol/L)`,na.rm = TRUE),
    "HDL Cholesterol (mmol/L)" = min(`HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "Non-HDL Cholesterol (mmol/L)" = min(`Non-HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "DNL (%)" = min(`DNL (%)`,na.rm = TRUE),
    "DNL (umol/L)" = min(`DNL (umol/L)`,na.rm = TRUE),
    "frGNG (%)" = min(`frGNG (%)`,na.rm = TRUE),
    "GNG (mmol/L)" = min(`GNG (mmol/L)`,na.rm = TRUE),
    "GLY (mmol/L)" = min(`GLY (mmol/L)`,na.rm = TRUE))

Liver_fat_mins <- as.data.frame(t(Liver_fat_mins[1:2,2:23])) %>% rename("Mins High" = V1, "Mins Low" = V2) %>% round(digits = 1)

Liver_fat_maxs <- All_data_split_df %>% 
  group_by(`Liver fat`) %>% 
  summarize(
    "IHTG (%)" = max(`IHTG (%)`,na.rm = TRUE),
    "Age" = max(`Age`, na.rm = TRUE), 
    "Weight (kg)" = max(`Weight (kg)`, na.rm = TRUE),  
    "BMI" = max(`BMI`, na.rm = TRUE), 
    "Waist Circumference (cm)" = max(`Waist Circumference (cm)`, na.rm = TRUE), 
    "Fat mass (%)" = max (`Fat mass (%)`, na.rm = TRUE), 
    "Lean mass (%)" = max(`Lean mass (%)`,na.rm = TRUE), 
    "Visceral fat mass (%)" = max(`Visceral fat mass (%)`,na.rm = TRUE),
    "Glucose (mmol/L)" = max(`Glucose (mmol/L)`,na.rm = TRUE),
    "Insulin (nmol/L)" = max(`Insulin (nmol/L)`,na.rm = TRUE),
    "HOMA-IR" = max(`HOMA-IR`,na.rm = TRUE),
    "NEFA (umol/L)" = max(`NEFA (umol/L)`,na.rm = TRUE),
    "TAG (umol/L)" = max(`TAG (umol/L)`,na.rm = TRUE),
    "3OHB (umol/L)" = max(`3OHB (umol/L)`,na.rm = TRUE),
    "Total Cholesterol (mmol/L)" = max(`Total Cholesterol (mmol/L)`,na.rm = TRUE),
    "HDL Cholesterol (mmol/L)" = max(`HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "Non-HDL Cholesterol (mmol/L)" = max(`Non-HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "DNL (%)" = max(`DNL (%)`,na.rm = TRUE),
    "DNL (umol/L)" = max(`DNL (umol/L)`,na.rm = TRUE),
    "frGNG (%)" = max(`frGNG (%)`,na.rm = TRUE),
    "GNG (mmol/L)" = max(`GNG (mmol/L)`,na.rm = TRUE),
    "GLY (mmol/L)" = max(`GLY (mmol/L)`,na.rm = TRUE))

Liver_fat_maxs <- as.data.frame(t(Liver_fat_maxs[1:2,2:23])) %>% rename("Maxs High" = V1, "Maxs Low" = V2) %>% round(digits = 1)



```
``` {R, tablulate!}

Liver_fat_table <- cbind(Liver_fat_medians, Liver_fat_mins, Liver_fat_maxs)

Liver_fat_table <- mutate(Liver_fat_table, "Low", "High")

for(i in 1:nrow(Liver_fat_table)) {
  Liver_fat_table[i,7] <- paste(Liver_fat_table[i,2], "(", Liver_fat_table[i,4], "-", Liver_fat_table[i,6], ")", sep = " ")
  Liver_fat_table[i,8] <- paste(Liver_fat_table[i,1], "(", Liver_fat_table[i,3], "-", Liver_fat_table[i,5], ")", sep = " ")
}

Liver_fat_table <- Liver_fat_table[,7:8]

Liver_fat_table

write.xlsx(Liver_fat_table, "Tables.xlsx", sheetName = "Liver fat", col.names = TRUE, row.names = TRUE, append = FALSE)

```

``` {r, Medians}

Insulin_medians <- All_data_split_df %>% 
  group_by(`Insulin`) %>% 
  summarize(
    "IHTG (%)" = median(`IHTG (%)`,na.rm = TRUE),
    "Age" = median(`Age`, na.rm = TRUE), 
    "Weight (kg)" = median(`Weight (kg)`, na.rm = TRUE),  
    "BMI" = median(`BMI`, na.rm = TRUE), 
    "Waist Circumference (cm)" = median(`Waist Circumference (cm)`, na.rm = TRUE), 
    "Fat mass (%)" = median (`Fat mass (%)`, na.rm = TRUE), 
    "Lean mass (%)" = median(`Lean mass (%)`,na.rm = TRUE), 
    "Visceral fat mass (%)" = median(`Visceral fat mass (%)`,na.rm = TRUE),
    "Glucose (mmol/L)" = median(`Glucose (mmol/L)`,na.rm = TRUE),
    "Insulin (nmol/L)" = median(`Insulin (nmol/L)`,na.rm = TRUE),
    "HOMA-IR" = median(`HOMA-IR`,na.rm = TRUE),
    "NEFA (umol/L)" = median(`NEFA (umol/L)`,na.rm = TRUE),
    "TAG (umol/L)" = median(`TAG (umol/L)`,na.rm = TRUE),
    "3OHB (umol/L)" = median(`3OHB (umol/L)`,na.rm = TRUE),
    "Total Cholesterol (mmol/L)" = median(`Total Cholesterol (mmol/L)`,na.rm = TRUE),
    "HDL Cholesterol (mmol/L)" = median(`HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "Non-HDL Cholesterol (mmol/L)" = median(`Non-HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "DNL (%)" = median(`DNL (%)`,na.rm = TRUE),
    "DNL (umol/L)" = median(`DNL (umol/L)`,na.rm = TRUE),
    "frGNG (%)" = median(`frGNG (%)`,na.rm = TRUE),
    "GNG (mmol/L)" = median(`GNG (mmol/L)`,na.rm = TRUE),
    "GLY (mmol/L)" = median(`GLY (mmol/L)`,na.rm = TRUE))

Insulin_medians <- as.data.frame(t(Insulin_medians[1:2,2:23])) %>% rename("Median High" = V1, "Median Low" = V2)%>%round(digits = 1)

```

``` {r, Ranges}

Insulin_mins <- All_data_split_df %>% 
  group_by(`Insulin`) %>% 
  summarize(
    "IHTG (%)" = min(`IHTG (%)`,na.rm = TRUE),
    "Age" = min(`Age`, na.rm = TRUE), 
    "Weight (kg)" = min(`Weight (kg)`, na.rm = TRUE),  
    "BMI" = min(`BMI`, na.rm = TRUE), 
    "Waist Circumference (cm)" = min(`Waist Circumference (cm)`, na.rm = TRUE), 
    "Fat mass (%)" = min (`Fat mass (%)`, na.rm = TRUE), 
    "Lean mass (%)" = min(`Lean mass (%)`,na.rm = TRUE), 
    "Visceral fat mass (%)" = min(`Visceral fat mass (%)`,na.rm = TRUE),
    "Glucose (mmol/L)" = min(`Glucose (mmol/L)`,na.rm = TRUE),
    "Insulin (nmol/L)" = min(`Insulin (nmol/L)`,na.rm = TRUE),
    "HOMA-IR" = min(`HOMA-IR`,na.rm = TRUE),
    "NEFA (umol/L)" = min(`NEFA (umol/L)`,na.rm = TRUE),
    "TAG (umol/L)" = min(`TAG (umol/L)`,na.rm = TRUE),
    "3OHB (umol/L)" = min(`3OHB (umol/L)`,na.rm = TRUE),
    "Total Cholesterol (mmol/L)" = min(`Total Cholesterol (mmol/L)`,na.rm = TRUE),
    "HDL Cholesterol (mmol/L)" = min(`HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "Non-HDL Cholesterol (mmol/L)" = min(`Non-HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "DNL (%)" = min(`DNL (%)`,na.rm = TRUE),
    "DNL (umol/L)" = min(`DNL (umol/L)`,na.rm = TRUE),
    "frGNG (%)" = min(`frGNG (%)`,na.rm = TRUE),
    "GNG (mmol/L)" = min(`GNG (mmol/L)`,na.rm = TRUE),
    "GLY (mmol/L)" = min(`GLY (mmol/L)`,na.rm = TRUE))

Insulin_mins <- as.data.frame(t(Insulin_mins[1:2,2:23])) %>% rename("Mins High" = V1, "Mins Low" = V2)%>%round(digits = 1)

Insulin_maxs <- All_data_split_df %>% 
  group_by(`Insulin`) %>% 
  summarize(
    "IHTG (%)" = max(`IHTG (%)`,na.rm = TRUE),
    "Age" = max(`Age`, na.rm = TRUE), 
    "Weight (kg)" = max(`Weight (kg)`, na.rm = TRUE),  
    "BMI" = max(`BMI`, na.rm = TRUE), 
    "Waist Circumference (cm)" = max(`Waist Circumference (cm)`, na.rm = TRUE), 
    "Fat mass (%)" = max (`Fat mass (%)`, na.rm = TRUE), 
    "Lean mass (%)" = max(`Lean mass (%)`,na.rm = TRUE), 
    "Visceral fat mass (%)" = max(`Visceral fat mass (%)`,na.rm = TRUE),
    "Glucose (mmol/L)" = max(`Glucose (mmol/L)`,na.rm = TRUE),
    "Insulin (nmol/L)" = max(`Insulin (nmol/L)`,na.rm = TRUE),
    "HOMA-IR" = max(`HOMA-IR`,na.rm = TRUE),
    "NEFA (umol/L)" = max(`NEFA (umol/L)`,na.rm = TRUE),
    "TAG (umol/L)" = max(`TAG (umol/L)`,na.rm = TRUE),
    "3OHB (umol/L)" = max(`3OHB (umol/L)`,na.rm = TRUE),
    "Total Cholesterol (mmol/L)" = max(`Total Cholesterol (mmol/L)`,na.rm = TRUE),
    "HDL Cholesterol (mmol/L)" = max(`HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "Non-HDL Cholesterol (mmol/L)" = max(`Non-HDL Cholesterol (mmol/L)`,na.rm = TRUE),
    "DNL (%)" = max(`DNL (%)`,na.rm = TRUE),
    "DNL (umol/L)" = max(`DNL (umol/L)`,na.rm = TRUE),
    "frGNG (%)" = max(`frGNG (%)`,na.rm = TRUE),
    "GNG (mmol/L)" = max(`GNG (mmol/L)`,na.rm = TRUE),
    "GLY (mmol/L)" = max(`GLY (mmol/L)`,na.rm = TRUE))


Insulin_maxs <- as.data.frame(t(Insulin_maxs[1:2,2:23])) %>% rename("Maxs High" = V1, "Maxs Low" = V2)%>%round(digits = 1)

```

``` {R, tablulate!}

Insulin_table <- cbind(Insulin_medians, Insulin_mins, Insulin_maxs)

Insulin_table <- mutate(Insulin_table, "Low", "High")

for(i in 1:nrow(Insulin_table)) {
  Insulin_table[i,7] <- paste(Insulin_table[i,2], "(", Insulin_table[i,4], "-", Insulin_table[i,6], ")", sep = " ")
  Insulin_table[i,8] <- paste(Insulin_table[i,1], "(", Insulin_table[i,3], "-", Insulin_table[i,5], ")", sep = " ")
}

Insulin_table <- Insulin_table[,7:8]

Insulin_table

write.xlsx(Insulin_table, "Tables.xlsx", sheetName = "Insulin", col.names = TRUE, row.names = TRUE, append = TRUE)

```
``` {R, QQ Plots}


ggqqplot(All_data$Age)
ggqqplot(All_data$`Weight (kg)`)
ggqqplot(All_data$BMI)
ggqqplot(All_data$`Waist Circumference (cm)`)
ggqqplot(All_data$`Fat mass (%)`)
ggqqplot(All_data$`Lean mass (%)`)
ggqqplot(All_data$`Visceral fat mass (%)`)
ggqqplot(All_data$`IHTG (%)`)
ggqqplot(All_data$`Glucose (mmol/L)`)
ggqqplot(All_data$`Insulin (nmol/L)`)
ggqqplot(All_data$`HOMA-IR`)
ggqqplot(All_data$`NEFA (umol/L)`)
ggqqplot(All_data$`TAG (umol/L)`)
ggqqplot(All_data$`3OHB (umol/L)`)
ggqqplot(All_data$`Total Cholesterol (mmol/L)`)
ggqqplot(All_data$`HDL Cholesterol (mmol/L)`)
ggqqplot(All_data$`Non-HDL Cholesterol (mmol/L)`)
ggqqplot(All_data$`DNL (%)`)
ggqqplot(All_data$`DNL (umol/L)`)
ggqqplot(All_data$`frGNG (%)`)
ggqqplot(All_data$`GNG (mmol/L)`)
ggqqplot(All_data$`GLY (mmol/L)`)


```
``` {r}

shapiro.test(All_data$Age)
shapiro.test(All_data$`Weight (kg)`)
shapiro.test(All_data$BMI)
shapiro.test(All_data$`Waist Circumference (cm)`)
shapiro.test(All_data$`Fat mass (%)`)
shapiro.test(All_data$`Lean mass (%)`)
shapiro.test(All_data$`Visceral fat mass (%)`)
shapiro.test(All_data$`IHTG (%)`)
shapiro.test(All_data$`Glucose (mmol/L)`)
shapiro.test(All_data$`Insulin (nmol/L)`)
shapiro.test(All_data$`HOMA-IR`)
shapiro.test(All_data$`NEFA (umol/L)`)
shapiro.test(All_data$`TAG (umol/L)`)
shapiro.test(All_data$`3OHB (umol/L)`)
shapiro.test(All_data$`Total Cholesterol (mmol/L)`)
shapiro.test(All_data$`HDL Cholesterol (mmol/L)`)
shapiro.test(All_data$`Non-HDL Cholesterol (mmol/L)`)
shapiro.test(All_data$`DNL (%)`)
shapiro.test(All_data$`DNL (umol/L)`)
shapiro.test(All_data$`frGNG (%)`)
shapiro.test(All_data$`GNG (mmol/L)`)
shapiro.test(All_data$`GLY (mmol/L)`)

#All significantly non-normally distributed except for Age, Fat mass and Lean mass!!

```
``` {r, non-parametric T testing (Mann-whitney U)}

Keepers <- c("Liver fat", "Insulin", row.names(Liver_fat_table))

All_data_split_filtered <- All_data_split_df[ , (names(All_data_split_df) %in% Keepers)]

All_data_split_filtered <- All_data_split_filtered[, c(23, 24, 1:22)]

All_data_split_filtered


for (i in 3:ncol(All_data_split_filtered)) {
   formula <- as.formula(paste("`", colnames(All_data_split_filtered)[i], "`", " ~ Insulin", sep=""))
   model <- wilcox.test(formula, data = All_data_split_filtered,
                   exact = FALSE)

   cat("\n-----\n\n")
   cat(colnames(All_data_split_filtered)[i])
   cat("\n")
   print(model)
}

```
